# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: 2i2c
  theme_night: 2i2c
  font: minimal
  font_size: M

# SEO

marketing:
  seo:
    site_type: Project
    local_business_type: ''
    org_name: '2i2c'
    description: 'The International Interactive Computing Collaboration.'
    twitter: '2i2c_org'
  analytics:
    google_analytics: 'UA-170352908-1'
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: |
      © {year} 2i2c. This work is licensed under {license}.
      <style>
      .footer__brand-icons {
        font-size: 1.3em;
        justify-content: center;
        display: flex;
        gap: .5rem;
      }
      </style>
      <div class="footer__brand-icons">
        <a href="https://github.com/2i2c-org/2i2c-org.github.io">
          <i class="fa-brands fa-github"></i>
        </a>
        <a href="https://twitter.com/2i2c_org">
          <i class="fa-brands fa-twitter"></i>
        </a>
        <a href="http://eepurl.com/hjHbff">
          <i class="fa-solid fa-envelope"></i>
        </a>
      </div>
    license:
      enable: true
      allow_derivatives: true
      share_alike: false
      allow_commercial: true

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - r
      - latex
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/<username>/<repository>'
    content_dir: content
    branch: master
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: master
    local_backend: false
  isotope:
    # Enable if you use the Portfolio widget or Publication filter
    enable: true
  academicons:
    enable: true